#!/bin/bash
set -e

ROLL_VERSION=${ROLL_VERSION:-"in-dev"}

# configure php additions.ini
sed -ie "s/{{ROLL_VERSION}}/${ROLL_VERSION}/g" /usr/share/nginx/html/index.html
sed -ie "s/{{ROLL_SERVICE_DOMAIN}}/${ROLL_SERVICE_DOMAIN}/g" /usr/share/nginx/html/index.html

# Start Nginx
nginx -g 'daemon off;'
