#!/bin/bash
set -e

get_latest_release() {
  curl --silent "https://api.github.com/repos/epartment/rolldev/releases/latest" | # Get latest release from GitHub api
    grep '"tag_name":' |                                            # Get tag line
    sed -E 's/.*"([^"]+)".*/\1/'                                    # Pluck JSON value
}

ROLL_VERSION=${ROLL_VERSION:-"in-dev"}
LATEST_RELEASE="$(get_latest_release)"

if [[ "$ROLL_VERSION" != "$LATEST_RELEASE" ]]; then
  sed -ie "s/class\=\"update hide\"/class\=\"update\"/g" /usr/share/nginx/html/index.html
  sed -ie "s/{{LATEST_RELEASE}}/${LATEST_RELEASE}/g" /usr/share/nginx/html/index.html
fi

# configure php additions.ini
sed -ie "s/{{ROLL_VERSION}}/${ROLL_VERSION}/g" /usr/share/nginx/html/index.html
sed -ie "s/{{ROLL_SERVICE_DOMAIN}}/${ROLL_SERVICE_DOMAIN}/g" /usr/share/nginx/html/index.html

# Start Nginx
nginx -g 'daemon off;'
