name: Docker Image MailHog
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # 6 AM Daily
  push:
    paths:
      - .trigger
      - mailhog/**
      - .github/workflows/*mailhog*

jobs:
  mailhog:
    name: MailHog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v5
        with:
          context: mailhog
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/mailhog:latest
        if: ${{ !env.ACT && github.ref == 'refs/heads/master'}}
